name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - self-hosted-ubuntu-2004
        node-version: [ 18.14.x ]

    steps:
    - uses: actions/checkout@v3
    - run: |
        npm install
        npm run all
    - uses: ./
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_URL: 'https://github.com/ry-itto.png'
        SLACK_USERNAME: 'Capicapi'
        SLACK_GITHUB_USER_PAIRS: ${{ secrets.SLACK_USER }}
        TITLE: ':tada: Success :tada:'
        BODY: 'ry-itto github octocat'

